[RS-2713] Handle case when logs are not aggregated during tests (#9555)
We sometimes have the following flake:
```
    waf_http_filter_test.go:363: 
        	Error Trace:	/go/src/github.com/projectcalico/calico/gateway/fv/waf_http_filter_test.go:368
        	            				/usr/local/go/src/runtime/asm_amd64.s:1700
        	Error:      	"[{"@timestamp":"2025-08-01T16:14:10.525764105Z","count":1,"destination":null,"level":"","method":"GET","msg":"WAF detected 2 violations [pass]","path":"/subpath?artist=0+div+1+union%23foo*%2F*bar%0D%0Aselect%23foo%0D%0A1%2C2%2Ccurrent_user","protocol":"HTTP/1.1","request_id":"8bb12496-8936-405f-84ba-f0e9ea5869f1","rules":[{"id":"942100","message":"SQL Injection Attack Detected via libinjection","severity":"critical","file":"@owasp_crs/REQUEST-942-APPLICATION-ATTACK-SQLI.conf","line":"5292","disruptive":false},{"id":"949111","message":"Inbound Anomaly Score Exceeded in phase 1 (Total Score: 5)","severity":"emergency","file":"@owasp_crs/REQUEST-949-BLOCKING-EVALUATION.conf","line":"7073","disruptive":false}],"source":{"ip":"192.168.122.33","port_num":55550},"host":"","gateway_name":"-","gateway_namespace":"-"} {"@timestamp":"2025-08-01T16:14:10.532962486Z","count":1,"destination":null,"level":"","method":"POST","msg":"WAF detected 2 violations [pass]","path":"/subpath?artist=0+div+1+union%23foo*%2F*bar%0D%0Aselect%23foo%0D%0A1%2C2%2Ccurrent_user","protocol":"HTTP/1.1","request_id":"42c291fa-09e7-40ce-854a-64354b64b3e9","rules":[{"id":"942100","message":"SQL Injection Attack Detected via libinjection","severity":"critical","file":"@owasp_crs/REQUEST-942-APPLICATION-ATTACK-SQLI.conf","line":"5292","disruptive":false},{"id":"949111","message":"Inbound Anomaly Score Exceeded in phase 1 (Total Score: 5)","severity":"emergency","file":"@owasp_crs/REQUEST-949-BLOCKING-EVALUATION.conf","line":"7073","disruptive":false}],"source":{"ip":"192.168.122.33","port_num":55550},"host":"","gateway_name":"-","gateway_namespace":"-"} ]" should have 2 item(s), but has 3
    waf_http_filter_test.go:363: 
        	Error Trace:	/go/src/github.com/projectcalico/calico/gateway/fv/waf_http_filter_test.go:363
        	Error:      	Condition never satisfied
        	Test:       	TestFileLogger
FAIL
FAIL	github.com/projectcalico/calico/gateway/fv	41.319s
FAIL
```

In this case we get 2 WAF logs instead of an aggregated one with a count of 2:
```
{"@timestamp":"2025-08-01T16:14:10.525764105Z","count":1,"destination":null,"level":"","method":"GET","msg":"WAF detected 2 violations [pass]","path":"/subpath?artist=0+div+1+union%23foo*%2F*bar%0D%0Aselect%23foo%0D%0A1%2C2%2Ccurrent_user","protocol":"HTTP/1.1","request_id":"8bb12496-8936-405f-84ba-f0e9ea5869f1","rules":[{"id":"942100","message":"SQL Injection Attack Detected via libinjection","severity":"critical","file":"@owasp_crs/REQUEST-942-APPLICATION-ATTACK-SQLI.conf","line":"5292","disruptive":false},{"id":"949111","message":"Inbound Anomaly Score Exceeded in phase 1 (Total Score: 5)","severity":"emergency","file":"@owasp_crs/REQUEST-949-BLOCKING-EVALUATION.conf","line":"7073","disruptive":false}],"source":{"ip":"192.168.122.33","port_num":55550},"host":"","gateway_name":"-","gateway_namespace":"-"}
{"@timestamp":"2025-08-01T16:14:10.532962486Z","count":1,"destination":null,"level":"","method":"POST","msg":"WAF detected 2 violations [pass]","path":"/subpath?artist=0+div+1+union%23foo*%2F*bar%0D%0Aselect%23foo%0D%0A1%2C2%2Ccurrent_user","protocol":"HTTP/1.1","request_id":"42c291fa-09e7-40ce-854a-64354b64b3e9","rules":[{"id":"942100","message":"SQL Injection Attack Detected via libinjection","severity":"critical","file":"@owasp_crs/REQUEST-942-APPLICATION-ATTACK-SQLI.conf","line":"5292","disruptive":false},{"id":"949111","message":"Inbound Anomaly Score Exceeded in phase 1 (Total Score: 5)","severity":"emergency","file":"@owasp_crs/REQUEST-949-BLOCKING-EVALUATION.conf","line":"7073","disruptive":false}],"source":{"ip":"192.168.122.33","port_num":55550},"host":"","gateway_name":"-","gateway_namespace":"-"}
```

My understanding is that the flake occurs when the aggregation period ends between the 2 requests. This PR updates the tests to deal with that case and make sure the content of the log file is what we expect.